# ========================================
# Nexus Wiki Configuration
# ========================================

# Site Metadata

site_name: Nexus Wiki
site_url: https://abhilashreddysh.github.io/wiki

# Theme Configuration

theme:
  name: material
  language: en
  custom_dir: custom

  # Icon Set
  icon:
    logo: material/rocket-launch
    repo: fontawesome/brands/github-alt
    edit: material/pencil-outline
    view: material/eye-outline

  # Typography Settings
  # font:
  #   text: "Roboto"
  #   code: "JetBrains Mono"
  #   text_weight: 300
  #   code_weight: 400

  # Color Schemes - Only dark mode
  palette:
    - scheme: slate
      primary: custom
      accent: custom

  # Features
  features:
    # Navigation Enhancements
    - navigation.instant # Enables instant page transitions without full reloads
    - navigation.tabs # Adds tabbed navigation for top-level sections
    - navigation.tabs.sticky # Keeps tabs visible while scrolling
    - navigation.sections # Enables section-based navigation in sidebar
    - navigation.top # Adds "back to top" button
    - navigation.indexes # Improves automatic index page generation
    - navigation.keyboard # Enables keyboard navigation
    # - navigation.expand # Expand all collapsible subsections by default

    # Code Display Features
    - content.code.copy # Adds copy button to code blocks (better UX for code snippets)
    - content.code.annotate # Allows code annotations (useful for documentation)

    # Search Improvements
    - search.highlight # Highlights search terms in results (better visibility)
    - search.suggest # Provides search suggestions as you type (faster finding)

    # Table of Contents
    - toc.follow # TOC highlights current section (better orientation)

    # Header Behavior
    - header.autohide # Auto-hides header when scrolling down (more reading space)

    # Content Interaction
    - content.tabs.link # Makes tabs linkable (shareable state)
    - content.tooltips # Enables tooltips (additional info on hover)
    - content.emoji # Enables emoji support (visual expression)

    # Edit/View Options
    - content.action.edit # Adds "edit this page" button (faster contributions)
    - content.action.view # Adds "view source" button (transparency)

# Repository & Editing
repo_name: abhilashreddysh/wiki
repo_url: https://github.com/abhilashreddysh/wiki
edit_uri: edit/main/docs/

# Custom Components
extra:
  # Social Links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abhilashreddysh
      name: GitHub Profile
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sh-abhilash
      name: LinkedIn Profile
    - icon: fontawesome/solid/envelope
      link: mailto:abhilashreddy723@gmail.com
      name: Email Contact

# Markdown Extensions

markdown_extensions:
  # Core Markdown Features
  - meta # Adds YAML metadata support (for page frontmatter)
  - tables # Enables GitHub-flavored markdown tables
  - footnotes # Adds footnote support ([^1] syntax)
  - attr_list # Allows HTML attributes in markdown ({: .class #id })
  - md_in_html # Allows markdown within HTML blocks
  - def_list # Enables definition lists (Term: Definition)

  # Navigation & Structure
  - toc: # Table of Contents generation
      permalink: ⚓︎ # Adds anchor link icon next to headings
      toc_depth: 3 # Shows headings up to level 3 (h1-h3) in TOC

  # UI Components
  - admonition # Creates note/warning/danger boxes (!!! syntax)
  - pymdownx.details # Adds expandable/collapsible sections (<details>)
  - pymdownx.tabbed: # Enables tabbed content sections
      alternate_style: true # Uses Material's styled tabs instead of default
  # - pymdownx.tasklist: # Enhanced task lists with customizable checkboxes
  #     custom_checkbox: true # Allows styling checkboxes

  # Code Handling
  - pymdownx.superfences # Better code fence handlingt
  - pymdownx.highlight: # Syntax highlighting
      anchor_linenums: true # Adds anchors to line numbers
      line_spans: __line # Allows targeting specific lines with CSS
      pygments_lang_class: true # Adds language-specific CSS classes
  - pymdownx.inlinehilite # Inline code highlighting (`code`{:.lang})

  # Emoji & Symbols
  - pymdownx.emoji: # Emoji support (:smile: syntax)
      emoji_index:
        !!python/name:material.extensions.emoji.twemoji # Uses Twitter emoji set


      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        # Renders as SVG
        # Utility Extensions


  - pymdownx.snippets # Allows file inclusion (like {% include "file.md" %})
# Plugins
plugins:
  - search
  - tags

# Additional Assets & Resources
extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/js/custom.js

# Footer & Legal
copyright: "&copy; Abhilash Reddy • Every error is a lesson • For personal learning and experimentation only. Use at your own risk."
