# Project information
site_name: Abhi's LearnOps
site_url: http://abhilashreddysh.github.io/wiki
site_author: Abhilash Reddy
site_description: >-
  Documentaion site

# Theme Conf
theme:
  name: material
  favicon: img/favicon.png
  #  for light and dark mode switch
  palette:
    # Light Mode
    - scheme: default
      primary: lime
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark Mode
    - scheme: slate
      primary: red
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/home-automation
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye

  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tabs
    - content.code.copy
    - search.highlight
    - search.suggest
    - content.action.edit
    - content.action.view
    - toc.follow
    - navigation.top

# Repository
repo_name: abhilashreddysh/wiki
repo_url: https://github.com/abhilashreddysh/wiki
edit_uri: ./edit/main/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abhilashreddysh
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/sh-abhilash

# Extensions
markdown_extensions:
  - md_in_html
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
