/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  wikiSidebar: [{ type: "autogenerated", dirName: "." }], // '.' means the current docs folder
};

module.exports = sidebars;
